### ISSUE TITLE
Error on startup AttributeError: module 'robin_stocks' has no attribute 'login'

### ISSUE THREAD

**Issue by downrightmike** [JasonRBowling/cryptoTradingBot#6]
Original program no mods:
Loading Config...
Status Email: 
Buy Limit 0.75%
Sell Limit 1.0%
Trades enabled: False
RSI Window: 48
MA Window: 24
Consecutive prices required: 48

No state saved, starting from scratch.
BCH
Creating coin BCH
ETH
Creating coin ETH
/home/test/lib/python3.6/site-packages/robin_stocks/__init__.py
['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', 'gemini', 'robinhood', 'tda']
Traceback (most recent call last):
  File "tidepool-v0.6.0.py", line 523, in <module>
    main()
  File "tidepool-v0.6.0.py", line 518, in main
    m = moneyBot()
  File "tidepool-v0.6.0.py", line 81, in __init__
    loginResult = rh.login(self.rh_user, self.rh_pw)
AttributeError: module 'robin_stocks' has no attribute 'login'

Other apps using the robin_stocks in the same virtualenv work just fine.

**Comment by bretthanus** [comment]
line 79 for the r.login i changed to match the latest robin-hood from the wiki, adding the "robinhood.authentication." between the r. and login:
```
        self.data = self.loadDataframe()
        Result = r.robinhood.authentication.login(self.rh_user, self.rh_pw)
        #print("\n")
        #print(loginResult)
        #print("\n")
        self.getIncrements()
```

i had to repeat for the remaining r. in the code- maybe 6-7 places- the r.get_crypto_quote became:r.robinhood.orders.get_crypto_quote:
```
        for c in self.coinList:
            try:
                result = r.robinhood.orders.get_crypto_quote(c)
                price = result['mark_price']
            except:
                print("An exception occurred retrieving prices.")
                return emptyDict
```
I had to change the phoenix account line as well from:
````
        for c in self.coinList:
            try:
                result = r.robinhood.orders.get_crypto_quote(c)
                price = result['mark_price']
            except:
                print("An exception occurred retrieving prices.")
                return emptyDict

```
to:
```
        try:
            me = r.robinhood.account.load_phoenix_account(info=None)
            cash = float(me['crypto_buying_power']['amount'])
        except:
```

this got me running this morning- after 48 datapoints though, when trying to trade, i got an error:
Traceback (most recent call last):
  File "tidepool-v0.9.0.py", line 520, in <module>
    main()
  File "tidepool-v0.9.0.py", line 516, in main
    m.runBot()
  File "tidepool-v0.9.0.py", line 504, in runBot
    if self.checkSellCondition(c) and self.pricesGood == True:
  File "tidepool-v0.9.0.py", line 304, in checkSellCondition
    if price > self.coinState[c].purchasedPrice + (self.coinState[c].purchasedPrice * self.sellAboveBuyPrice) and self.coinState[c].numHeld > 0.0:
IndexError: list index out of range

I havent figured this one out yet though...

**Comment by downrightmike** [comment]
I solved this by rebuilding the virtualenv and that allowed it to function as expected.
